spring:
  mail:
    host: smtphz.qiye.163.com
    port: 994
    username: yogjunwork@163.com
    password: 123!
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          timeout: 30000
          socketFactory:
            port: ${spring.mail.port}
            fallback: false
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true